BOLD=\033[1m
GREEN=\033[32m
BLUE=\033[34m
YELLOW=\033[0;33m
RED=\033[31m
CYAN=\033[36m
MAGENTA=\033[35m
RESET=\033[0m
LINE=-----------------------------
# Add the requirements to the specified dependency group, --group dev
#CUSTOM_DEPS="--group dev"
CUSTOM_DEPS=""

# Install requirements (editable, dev) and sync uv.lock file
# Customize PKG_MANAGER if needed, e.g. to use pip instead of uv
.PHONY: help-setup install lint test test-watch test-clean setup setup-full

# Install & Sync dependencies with uv.lock for the given package
install:
	$(PKG_MANAGER) add --editable $(PACKAGE_PATH)

# Lint using Ruff (or flake8)
lint:
	ruff --check .

# Test commands
# Run tests once
test:
	$(PKG_MANAGER) pip install . --group test
	pytest

# Watch files & rerun on changes (optional: with pytest-watch)
test-watch:
	$(PKG_MANAGER) pip install --group test . pytest-watch
	ptw --ext .py

# Clean __pycache__ and .pytest_cache
test-clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	rm -rf .pytest_cache

# Setup: install, format, lint, test
setup: install lint test

# Make full installation: submodule-add install lint test
setup-full: submodule-add install lint test

list_user_variables:
	@echo "Variables in Makefile:"
	@echo "PACKAGE_REPO = $(PACKAGE_REPO)"
	@echo "PACKAGE_PATH = $(PACKAGE_PATH)"
	@echo "PKG_MANAGER = $(PKG_MANAGER)"
	@echo "CUSTOM_DEPS = $(CUSTOM_DEPS)"

.PHONY: help-setup
help-setup:
	@printf "${BOLD}SETUP: Available targets:${RESET}\n"
	@printf "${CYAN}$(LINE)${RESET}\n"
	@echo "  install          	- Install dependencies (editable + $(CUSTOM_DEPS))"
	@echo "  lint             	- Lint code with Ruff"
	@echo "  test             	- Run tests once with pytest"
	@echo "  test-watch       	- Watch files & rerun on changes (optional: with pytest-watch)"
	@echo "  test-clean       	- Clean cache files, eg. __pycache__ and .pytest_cache"
	@echo "  setup            	- Install and check everything"
	@echo "  setup-full        	- Make full installation: submodule-add install lint test"
	@echo "  list_user_variables	- List user-defined variables in Makefile"
	@echo "  help             	- Show this help message"
	@echo

